import Homepage from './Homepage'
import SignUp from './SignUp'
import Login from './Login'
import Profil from './Profil'
import Products from './Products'
import ProductDetails from './ProductDetails'
import ForgotPassword from './ForgotPassword'
import UserVerify from './UserVerify'
import Payment from './Payment'
import History from './HistoryPage'
import ChangePassword from './ChangePassword'
import AddProduct from './AddNewProduct'
import EditProduct from './EditExistProduct'

export {SignUp, Login, Profil, ForgotPassword, ProductDetails, Products, AddProduct, EditProduct, UserVerify, Homepage, Payment, History, ChangePassword}
